### GET request without parameters
GET http://localhost:8080/games/all
Accept: application/json

### GET request with parameter
GET http://localhost:8080/games/66acd000-77fe-1000-9115-d802584107ef
Accept: application/json

